/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResumeReviewRouteImport } from './routes/_authenticated/resume-review'
import { Route as AuthenticatedHrInterviewRouteImport } from './routes/_authenticated/hr-interview'
import { Route as AuthenticatedDsaPracticeRouteImport } from './routes/_authenticated/dsa-practice'
import { Route as AuthenticatedCompanyPrepRouteImport } from './routes/_authenticated/company-prep'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumeReviewRoute =
  AuthenticatedResumeReviewRouteImport.update({
    id: '/resume-review',
    path: '/resume-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrInterviewRoute =
  AuthenticatedHrInterviewRouteImport.update({
    id: '/hr-interview',
    path: '/hr-interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDsaPracticeRoute =
  AuthenticatedDsaPracticeRouteImport.update({
    id: '/dsa-practice',
    path: '/dsa-practice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyPrepRoute =
  AuthenticatedCompanyPrepRouteImport.update({
    id: '/company-prep',
    path: '/company-prep',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatRoute
  '/company-prep': typeof AuthenticatedCompanyPrepRoute
  '/dsa-practice': typeof AuthenticatedDsaPracticeRoute
  '/hr-interview': typeof AuthenticatedHrInterviewRoute
  '/resume-review': typeof AuthenticatedResumeReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatRoute
  '/company-prep': typeof AuthenticatedCompanyPrepRoute
  '/dsa-practice': typeof AuthenticatedDsaPracticeRoute
  '/hr-interview': typeof AuthenticatedHrInterviewRoute
  '/resume-review': typeof AuthenticatedResumeReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/company-prep': typeof AuthenticatedCompanyPrepRoute
  '/_authenticated/dsa-practice': typeof AuthenticatedDsaPracticeRoute
  '/_authenticated/hr-interview': typeof AuthenticatedHrInterviewRoute
  '/_authenticated/resume-review': typeof AuthenticatedResumeReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/chat'
    | '/company-prep'
    | '/dsa-practice'
    | '/hr-interview'
    | '/resume-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/chat'
    | '/company-prep'
    | '/dsa-practice'
    | '/hr-interview'
    | '/resume-review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/chat'
    | '/_authenticated/company-prep'
    | '/_authenticated/dsa-practice'
    | '/_authenticated/hr-interview'
    | '/_authenticated/resume-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume-review': {
      id: '/_authenticated/resume-review'
      path: '/resume-review'
      fullPath: '/resume-review'
      preLoaderRoute: typeof AuthenticatedResumeReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr-interview': {
      id: '/_authenticated/hr-interview'
      path: '/hr-interview'
      fullPath: '/hr-interview'
      preLoaderRoute: typeof AuthenticatedHrInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dsa-practice': {
      id: '/_authenticated/dsa-practice'
      path: '/dsa-practice'
      fullPath: '/dsa-practice'
      preLoaderRoute: typeof AuthenticatedDsaPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-prep': {
      id: '/_authenticated/company-prep'
      path: '/company-prep'
      fullPath: '/company-prep'
      preLoaderRoute: typeof AuthenticatedCompanyPrepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCompanyPrepRoute: typeof AuthenticatedCompanyPrepRoute
  AuthenticatedDsaPracticeRoute: typeof AuthenticatedDsaPracticeRoute
  AuthenticatedHrInterviewRoute: typeof AuthenticatedHrInterviewRoute
  AuthenticatedResumeReviewRoute: typeof AuthenticatedResumeReviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCompanyPrepRoute: AuthenticatedCompanyPrepRoute,
  AuthenticatedDsaPracticeRoute: AuthenticatedDsaPracticeRoute,
  AuthenticatedHrInterviewRoute: AuthenticatedHrInterviewRoute,
  AuthenticatedResumeReviewRoute: AuthenticatedResumeReviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
